version: '3'
services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - my-network
  search-microservice:
    build:
      context: ./search_microservice
    ports:
      - "5001:5000"
    depends_on:
      - mysql
    networks:
      - my-network
  rezervari-microservice:
    build:
      context: ./rezervari_microservice
    ports:
      - "5002:5000"
    depends_on:
      - mysql
    networks:
      - my-network
  mysql:
    image: mysql:latest
    command: [ "--init-file", "/docker-entrypoint-initdb.d/init.sql" ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: localhost
      MYSQL_DATABASE: library_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - my-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - flask-app
    networks:
      - my-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
networks:
  my-network:
    driver: bridge
